import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container flex min-h-screen min-w-full flex-col pl-24 pr-24'>
          <nav className='p-8'>
            <ul className='flex items-center flex-row'>
              <li className='p-4'><a href="/">Front page</a></li>
              <li className='p-4'><a href="/stocks">Stocks</a></li>
            </ul>
          </nav>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
